#############################################################
## The below content is copied from _config-senior.yml
#############################################################

# Site
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Khanh Q. Chung
title: Lecturer | Embedded Engineer | DevOps Engineer
email: khanhcq@uit.edu.vn
phone: (+84) 907060401

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: reedus

# Additional icon links
additional_links:
- title: Location
  icon: fas fa-map-marker
  url: https://goo.gl/maps/7hL1KTYAgQnMWHeX8

# About Section
# about_title: About Me
about_profile_image: images/default.jpg
# about_profile_image: images/white-khanh.jpg
about_content: | # this will include new lines to allow paragraphs
  Dear Sir,

  My name is Khanh, and I have been a lecturer at the University of Information Technology in Vietnam for years. Working for other technology enterprises besides teaching is also one of my strengths. I'm currently seeking to undertake PhD research regarding the development of embedded systems and IoT field.

  I strongly believe that my ability and effort will be a good fit for the PhD position, and working in your group will be my best opportunity to show you my best.

  I'm looking forward to hearing answer from you soon.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 2012 MS in Computer Science
        sub_title: University of Science, Vietnam National University (VNU-HCM)
        caption: Thesis title "Study on Tag Anti-Collison using Time Division Multiple Access approach for the SELab MIFARE reader"
        quote: >
        description: | # this will include new lines to allow paragraphs

      - layout: top-middle
        title: 2009 BS in Computer Science
        sub_title: University of Science, Vietnam National University (VNU-HCM)
        caption: Excellent grade
        quote: >
        description: | # this will include new lines to allow paragraphs

  - title: Professional Appointments # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Lecturer at the Department of Embedded Systems and Robotics
        sub_title: University of Information Technology
        caption: 2016 - now
        quote: >
          Taught a total of 5 undergraduate courses. Supervised 5 BS theses.
        description: | # this will include new lines to allow paragraphs
          + Embedded Systems Programming course
          + Embedded Systems Design course
          + Microprocessor and Microcontroller course
          + Operating Systems course
          + Computer Organization course

      - layout: top
        title: Researcher at Software Engineering Laboratory
        sub_title: University of Science, VNU-HCM
        caption: 2010 - 2015
        quote: >
          Conducted 4 useful research projects for the Department of Science and Technology Ho Chi Minh city in Vietnam.
        description: | # this will include new lines to allow paragraphs
          + Researched and made a NFC reader/writer using MFRC522 MCU. This small gadget supports various kinds of NFC tags, including 1K/4K, Ultralight and DESFire EV1.
          + Built a data capture device via RS232 and USB interface. This device would be plugged into any bill printer to collect every single byte of data printed.
          + Built a time attendance system based on S3C2440-ARM9-based board. The cool thing was that each user's fingerprint minutiae was stored in their RFID tag instead of using a centralized database.
          + Developed a C Compiler for a domestic 8-bit MCU named SG8V1.

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Remote Embedded Software Engineer
        sub_title: Harman R&D Center (A Samsung Company), Suzhou, China
        caption: 2022 - now
        quote: >
        description: | # this will include new lines to allow paragraphs
          + Developed new features related to system management including battery, thermal, poweric, self reset.

      - layout: top
        title: Embedded Engineer, DevOps Engineer
        sub_title: Leanwell Technology Co., Ltd
        caption: 2017 - 2021
        quote: >
          My main aim in this startup was to collect as much data as possible by creating IoT devices.
        description: | # this will include new lines to allow paragraphs
          + Led an IoT team of 4 staff in researching and building commercial embedded products.
          + Deployed 500+ embedded devices at clients' factories.
          + Managed to bridge the gap between the software development team and IT operation guys at the client sites: deploy software releases as quickly as possible,
          ensure that services are easily scalable as well as have the ability of high availability, and protect servers against hackers.
          + Set up mass production processes for all embedded products.

      - layout: top
        title: Embedded Software Engineer
        sub_title: ZenithTek Co., Ltd
        caption: 2012 - 2015
        quote: >
          My goal.
        description: | # this will include new lines to allow paragraphs
          + Worked closely with a hardware guy to design and develop a compact embedded device that is similar to Raspberry Pi.
          + Created a hacked version of a tape dispenser device in which an in-house board was injected into the original device to make it smarter.
          + Deployed nearly 150 embedded devices that closely integrated with web applications on quality control lines at clients' factories => completely replaced paperwork and improved performance by around 20%.

      - layout: top
        title: Embedded Software Internship
        sub_title: NXP Semiconductors Vietnam
        caption: 09/2008 - 12/2008
        quote: >
          The laboratory where I did my thesis had established a partner relationship with NXP Vietnam; therefore, I luckily had a chance to carry out the BS thesis
          under expert guidance and the professional workplace.
        description: | # this will include new lines to allow paragraphs
          + Developed a lightweight USB host library running on the MCB2388 evaluation board. This library complies with USB 2.0 Specification and provides three USB classes including Audio, Human Interface Device (HID) and Mass Storage.

# Footer
footer_show_references: true
references_title: reenor.github.io

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag